[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from="/api/"
  to="https://api.ossn.club/"
  to="http://0.0.0.0:3000/api/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
